{
 "title": "Postgres IOPS for PG 16+",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Write IOPS by Backend Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_io_writes_total[1m])) by (backend_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Throughput kB/s by Backend Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_io_writes_total[1m])) by (backend_type) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read IOPS Backend Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(pg_io_reads_total[1m])) by (backend_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throughput in KB/s Backend Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(pg_io_reads_total[1m])) by (backend_type) * 8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}